routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

// ############################# USERS #################################################
// Route::get('/login', 'DashboardController@login')->name('user.login');
// Route::post('/login', 'DashboardController@auth')->name('user.logar');
// Route::get('/logout', 'DashboardController@logout')->name('user.logout');

// ############################# SERVIÇOS ###############################################
Route::resource('servico', 'ServicesController');
Route::get('/servico/user/{user}', 'ServicesController@openService')->name('servico.openService');
Route::get('/showCloseService', 'ServicesController@showCloseService')->name('servico.showCloseService');
Route::get('/closeService', 'ServicesController@closeService')->name('servico.closeService');
Route::get('/confirmaCloseService', 'ServicesController@confirmaCloseService')->name('servico.confirmaCloseService');

// ############################### ROTAS AUTENTICADAS ####################################
Route::middleware('auth')->group(function () {

// ################################ HOME #################################################
    Route::get('/home', 'HomeController@index')->name('home');

// ##################################### DASHBOARD #################################################
    Route::any('/dashboard/CmtGda', 'Dashboard\DashboardCmtGdaController@index')->name('dashboard.cmtgda');
    Route::any('/dashboard/OfiDia', 'Dashboard\DashboardOfiDiaController@index')->name('dashboard.ofidia');

// ############################# USUARIOS #################################################
    Route::resource('usuarios', 'UsersController');

// ############################## POSTO / GRADUAÇÃO #######################################
    Route::resource('postograduacao', 'PostosController');

// ############################## MOTORISTA ###############################################
    Route::resource('motoristas', 'MotoristasController');

// ############################### CHEFE DE VIATURA #######################################
    Route::resource('chefeviatura', 'ChefeViaturasController');

// ############################## ACESSOS #################################################
    Route::resource('acessos', 'RolesController');

// ############################# VIATURAS #################################################
    Route::resource('viaturas', 'ViaturasController');

// ############################# REGISTRO DE SAIDA DE VIATURAS #############################
    Route::resource('registroViaturas', 'RegistroViaturasController');
    Route::get('/registroViatura/corrigir/{registroViaturaOficial}', 'RegistroViaturasController@corrigirRegistroShow')->name('registroViatura.corrigirRegistro');
    Route::put('/registroViatura/{registroViaturaOficial}/update', 'RegistroViaturasController@corrigirRegistroUpdate')->name('registroViatura.corrigirRegistroUpdate');
    Route::get('/registroViatura/motorista', 'RegistroViaturasController@motoristaCreate')->name('registroViatura.motoristaCreate');
    Route::post('/registroViatura/motorista', 'RegistroViaturasController@motoristaStore')->name('registroViatura.motoristaStore');
    Route::get('/registroViatura/chefeviatura', 'RegistroViaturasController@chefeViaturaCreate')->name('registroViatura.chefeViaturaCreate');
    Route::post('/registroViatura/chefeviatura', 'RegistroViaturasController@chefeViaturaStore')->name('registroViatura.chefeViaturaStore');

// ############################# REGISTRO DE ENTRADA DE VIATURA ############################
    Route::resource('registroViaturaEntradas', 'RegistroViaturaEntradasController');

// ############################# REGISTRO DE ENTRADA DE MILITARES #############################
    Route::resource('registroMilitares', 'RegistroMilitarsController');
    Route::get('/registroMilitares/corrigir/{registroViaturaOficial}', 'RegistroMilitarsController@corrigirRegistroShow')->name('registroMilitares.corrigirRegistro');
    Route::put('/registroMilitares/{registromilitaresOficial}/update', 'RegistroMilitarsController@corrigirRegistroUpdate')->name('registroMilitares.corrigirRegistroUpdate');

// ############################# REGISTRO DE SAIDA DE VIATURA ############################
    Route::resource('registroMilitarSaidas', 'RegistroMilitarSaidasController');

// ############################# REGISTRO DE VIATURA OFICIAL ###############################
    Route::get('/registroViaturaOficial', 'RegistroViaturaOficialsController@index')->name('registroViaturaOficial.index');
    Route::get('/registroViaturaOficial/{registroViaturaOficial}', 'RegistroViaturaOficialsController@show')->name('registroViaturaOficial.show');
    Route::put('/registroViaturaOficial/{registroViaturaOficial}/edit', 'RegistroViaturaOficialsController@edit')->name('registroViaturaOficial.edit');
    Route::get('/registroViaturaOficial/finalizarRegistro/{finalizarRegistro}', 'RegistroViaturaOficialsController@finalizarRegistro')->name('registroViaturaOficial.finalizarRegistro');
    Route::get('/trocarCmtGda', 'RegistroViaturaOficialsController@trocarCmtGda')->name('registroViaturaOficial.trocarCmtGda');
    Route::put('/trocarCmtGda/{trocarCmtGda}/update', 'RegistroViaturaOficialsController@trocarCmtGdaUpdate')->name('registroViaturaOficial.trocarCmtGdaUpdate');
    Route::any('/registroViaturaOficial/relatorios/pdf', 'RegistroViaturaOficialsController@viaturasPdf')->name('registroViaturaOficial.viaturasPdf');
    Route::any('/registroViaturaOficial/relatorios/pdf/gerar', 'RegistroViaturaOficialsController@gerarViaturasPdf')->name('registroViaturaOficial.gerarViaturasPdf');

// ############################# REGISTRO DE MILITARES OFICIAL ###############################
    Route::get('/registroMilitarOficial', 'RegistroMilitarOficialsController@index')->name('registroMilitarOficial.index');
    Route::get('/registroMilitarOficial/{registroMilitarOficial}', 'RegistroMilitarOficialsController@show')->name('registroMilitarOficial.show');
    Route::put('/registroMilitarOficial/{registroMilitarOficial}/edit', 'RegistroMilitarOficialsController@edit')->name('registroMilitarOficial.edit');
    Route::get('/registroMilitarOficial/finalizarRegistro/{finalizarRegistro}', 'RegistroMilitarOficialsController@finalizarRegistro')->name('registroMilitarOficial.finalizarRegistro');
    Route::any('/registroMilitarOficial/relatorios/pdf', 'RegistroMilitarOficialsController@militaresPdf')->name('registroMilitarOficial.militaresPdf');
    Route::any('/registroMilitarOficial/relatorios/pdf/gerar', 'RegistroMilitarOficialsController@gerarMilitaresPdf')->name('registroMilitarOficial.gerarViaturasPdf');

// ######################################### GESTOR #########################################
    Route::get('/dashboard/gestor', 'GestorController@dashboard')->name('gestor.dashboard');
    Route::get('/report/viaturas', 'GestorController@dashboardViaturasPdf')->name('gestor.dashboardViaturasPdf');
    Route::get('/report/viaturas/pdf', 'GestorController@dashboardGerarViaturasPdf')->name('gestor.dashboardGerarViaturasPdf');
    Route::get('/report/viaturas/{report}', 'GestorController@viaturasPdf')->name('gestor.viaturasPdf');
    Route::get('/report/viaturas/pdf/{report}', 'GestorController@gerarViaturasPdf')->name('gestor.gerarViaturasPdf');
    // ################### SERVIÇO ###################
    Route::get('/report/servico', 'GestorController@servico')->name('gestor.reportServico');
    Route::post('/report/servicoShow', 'GestorController@servicoShow')->name('gestor.reportServicoShow');
    Route::post('/report/servicoDataShow', 'GestorController@servicoDataShow')->name('gestor.reportServicoDataShow');
    // ################### SERVIÇO OFICIAL ###################
    Route::get('/report/servico/oficial', 'GestorController@servicoOficial')->name('gestor.reportServicoOficial');
    Route::post('/report/servico/oficialShow', 'GestorController@servicoOficialShow')->name('gestor.reportServicoOficialShow');
    // ################### SERVIÇO CMT GDA ###################
    Route::get('/report/servico/cmtGda', 'GestorController@servicoCmtGda')->name('gestor.reportServicoCmtGda');
    Route::post('/report/servico/cmtGdaShow', 'GestorController@servicoCmtGdaShow')->name('gestor.reportServicoCmtGdaShow');
    // ################### VIATURA ###################
    Route::get('/report/viatura', 'GestorController@viatura')->name('gestor.reportViatura');
    Route::post('/report/viaturaShow', 'GestorController@viaturaShow')->name('gestor.reportViaturaShow');
    Route::post('/report/viaturaDataShow', 'GestorController@viaturaDataShow')->name('gestor.reportViaturaDataShow');
});

app/Http/Controllers/ChefeViaturasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\PostoRepository;
use App\Services\ChefeViaturasService;

use App\Http\Requests\ChefeViaturaCreateRequest;
use App\Http\Requests\ChefeViaturaUpdateRequest;
use App\Repositories\ChefeViaturaRepository;

class ChefeViaturasController extends Controller
{
    protected $repository;
    protected $service;
    protected $postoRepository;

    public function __construct(ChefeViaturaRepository $repository, ChefeViaturasService $service, PostoRepository $postoRepository)
    {
        $this->repository = $repository;
        $this->service = $service;
        $this->postoRepository = $postoRepository;
    }

    public function index()
    {
        $chefeViaturas = $this->repository->all();
        return view('painel.chefeViatura.index', compact('chefeViaturas'));
    }

    public function create()
    {
        $postoGraduacao = $this->postoRepository->findWhereNotIn('id', [1]);
        return view('painel.chefeViatura.createEdit', compact('postoGraduacao'));
    }

    public function store(ChefeViaturaCreateRequest $request)
    {
        if ($this->service->checaChefeViaturaCreate($request->all()))
            return redirect()->route('chefeviatura.index');

        $chefeviatura = $this->service->store($request->all());

        session()->flash('success', [
            'success' => $chefeviatura['success'],
            'messages' => $chefeviatura['messages']
        ]);

        return redirect()->route('chefeviatura.index');
    }

    public function edit($id)
    {
        $chefeViatura = $this->repository->find($id);
        $postoGraduacao = $this->postoRepository->all();

        return view('painel.chefeViatura.createEdit', compact('chefeViatura', 'postoGraduacao'));
    }

    public function update(ChefeViaturaUpdateRequest $request, $id)
    {
        if ($this->service->checaChefeViaturaUpdate($request->all(), $id))
            return redirect()->route('chefeviatura.index');

        $chefeviatura = $this->service->update($request->all(), $id);

        session()->flash('success', [
            'success' => $chefeviatura['success'],
            'messages' => $chefeviatura['messages']
        ]);

        return redirect()->route('chefeviatura.index');
    }

    public function show($id)
    {
        $chefeViatura = $this->repository->find($id);

        return view('painel.chefeViatura.show', compact('chefeViatura'));
    }

    public function destroy($id)
    {
        $chefeviatura = $this->service->destroy($id);

        session()->flash('success', [
            'success' => $chefeviatura['success'],
            'messages' => $chefeviatura['messages'],
        ]);

        return redirect()->route('chefeviatura.index');
    }

}

resources/views/painel/chefeViatura/createEdit.blade.php
@extends('layouts.mastertop')

@section('content')
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-xs-12 col-md-6">
            <div id="result"></div>
            <div class="box box">
                <div style="background-color: #808000; color:beige" class="box-header with-border">
                    @if(isset($chefeViatura))
                        <h3><i class="fa fa-car"></i> Alterar Chefe de Viatura</h3>
                        {!! Form::model($chefeViatura, ['route' => ['chefeviatura.update', $chefeViatura->id], 'method' => 'put']) !!}
                    @else
                        <h3><i class="fa fa-car"></i> Cadastrar Chefe de Viatura</h3>
                        {!! Form::open(['route' => 'chefeviatura.store', 'method' => 'post']) !!}
                    @endif
                    <h5>Registrar todos os Chefes de Viatura da OM.</h5>
                </div>

                @include('layouts.alerts.validationAlert')
                <div class="box-body">

                    <div class="form-group">
                        <label>Nome Completo</label>
                        {!! Form::text('nome_completo', $value = null, ['class' => 'form-control', 'autofocus']) !!}
                    </div>

                    <div class="form-group">
                        <label>Posto Graduação</label>
                        {!! Form::select('posto_id', $postoGraduacao->pluck('name', 'id'), null, ['class' => 'form-control flat select2', 'style' => 'width: 100%']) !!}
                    </div>
                    <div class="form-group">
                        <label>Nome de Guerra</label>
                        {!! Form::text('nome_guerra', $value = null, ['class' => 'form-control', 'placeholder' => 'Somente o Nome de Guerra sem posto e graduação']) !!}
                    </div>

                    <div class="form-group">
                        <label>Cpf</label>
                        {!! Form::text('cpf', $value = null, ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        <label> Ativo </label>
                        <label>{!! Form::radio('status', 1, isset($chefeViatura->status) ? ($chefeViatura->status == 1) ? true : false : true) !!}</label>
                    </div>
                    <div class="form-group">
                        <label> Inativo </label>
                        <label>{!! Form::radio('status', 0, isset($chefeViatura->status) ? ($chefeViatura->status == 0) ? true : false : false) !!}</label>
                    </div>
                </div>
                <div class="modal-footer">
                    {!! Form::submit(isset($chefeViatura) ? 'Alterar' : 'Cadastrar', ['class' => 'btn flat btn-oliva']) !!}
                    <a href="{{ route('chefeviatura.index') }}"
                       class="btn btn-oliva flat">Fechar</a>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

@push('datatables-css')
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/iCheck/all.css') }}">
    <link rel="stylesheet" href="{{ asset('adminlte/components/select2/dist/css/select2.min.css') }}">
@endpush

@push('datatables-script')
    <script src="{{ asset('adminlte/plugins/iCheck/icheck.min.js') }}"></script>
    <script src="{{ asset('adminlte/components/select2/dist/js/select2.full.min.js') }}"></script>

    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();

            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            })

            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass   : 'iradio_minimal-red'
            })
        })
    </script>

@endpush 

resources/views/painel/chefeViatura/index.blade.php
@extends('layouts.mastertop')

@section('content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box box">
                <div class="box-header with-border">
                    <h3><i class="fa fa-list"></i> Cadastro de Chefe de Viatura</h3>
                    Todos os chefe de viaturas da OM
                    <a class="btn btn-primary btn-flat btn-oliva pull-right"
                       href="{{ route('chefeviatura.create') }}"><i class="fa fa-users"></i> Cadastrar</a>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead class="table_blue">
                        <tr>
                            <th>Nome Completo</th>
                            <th>Nome de Guerra</th>
                            <th>Cpf</th>
                            <th>Status</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(isset($chefeViaturas))
                            @foreach($chefeViaturas as $chefeviatura)
                                <tr>
                                    <td>{{ $chefeviatura->nome_completo }}</td>
                                    <td>{{ $chefeviatura->getPostoName->name_abreviado . ' ' . $chefeviatura->nome_guerra  }}</td>
                                    <td>{{ isset($chefeviatura->cpf) ? $chefeviatura->cpf : 'Não Informado' }}</td>
                                    <td style="text-align: center">
                                        @if($chefeviatura->status == 1)
                                            <span class="badge bg-green">ATIVO</span></td>
                                    @else
                                        <span class="badge bg-red">INATIVO</span></td>
                                    @endif
                                    <td style="text-align: center">
                                        <div style="margin-right:5px" class="btn-group">
                                            <a href="{{ route('chefeviatura.edit', $chefeviatura->id) }}"
                                               data-toggle="tooltip" data-placement="top"
                                               title="Editar Registro"> <i
                                                        class='fa fa-pencil text-primary'></i></a>
                                        </div>
                                        <div style="margin-right:5px" class="btn-group">
                                            <a href="{{ route('chefeviatura.show', $chefeviatura->id) }}"
                                               data-toggle="tooltip" data-placement="top"
                                               title="Excluir Registro"> <i
                                                        class='fa fa-trash text-red'></i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('datatables-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('adminlte/components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endpush

@push('datatables-script')
    <!-- DataTables -->
    <script src="{{ asset('adminlte/components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('adminlte/components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
    <script src="{{ asset('pikeadmin/js/sweetalertsaw.min.js') }}"></script>

    <script>
        $(function () {
            $("#example1").DataTable(
                {
                    "language": {
                        "url": "/adminlte/components/datatables.net/js/ptBr.lang"
                    }
                }
            )
        });
    </script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="popover"]').popover()
        })
    </script>
@endpush

resources/views/painel/chefeViatura/show.blade.php
@extends('layouts.mastertop')

@section('content')


    <!-- Modal -->
    <div class="modal fade custom-modal" data-backdrop="static" id="modal-sucess" tabindex="1" role="dialog"
         aria-labelledby="customModal" aria-hidden="true">
        <div class="modal-dialog" style="width: 600px">
            <div class="modal-content">
                <div class="modal-header-delete">
                    <h3><i class="fa fa-trash-o"></i> Excluir Chefe de Viatura</h3>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="box-body">
                                <div class="row">
                                    <!-- /.col -->
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nome:</label>
                                            <p>{{ $chefeViatura->nome_completo }}</p>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Nome de Guerra:</label>
                                            <p>{{ $chefeViatura->getPostoName->name_abreviado . ' ' . $chefeViatura->nome_guerra }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Cpf:</label>
                                            <p>{{ isset($chefeViatura->cpf) ? $chefeViatura->cpf : 'Não Informado' }}</p>
                                            <!-- /.input group -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    {!! Form::open(['route' => ['chefeviatura.destroy', $chefeViatura->id], 'method' => 'DELETE']) !!}
                    {!! Form::submit('Excluir', ['class' => 'btn flat btn-oliva']) !!}
                    <a href="{{ route('chefeviatura.index') }}" class="btn btn-oliva flat">Voltar</a>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@push('datatables-css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('adminlte/plugins/timepicker/bootstrap-timepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('pikeadmin/css/style.css') }}">
@endpush

@push('datatables-script')
    <!-- DataTables -->
    <script src="{{ asset('pikeadmin/components/popper/popper.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
    <script src="{{ asset('adminlte/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>

    <script>
        $(document).ready(function () {
            $('#modal-sucess').modal('show');
        });
    </script>
@endpush